[package]
name = "json_schema"
version = "0.1.0"
authors = ["Jordan McQueen <jordan@whoami.sh>"]
edition = "2018"

[dependencies]
serde_json = "~1.0.4"
serde = {version = "~1.0.4", features = ["derive"]}
